.pragma library

const CHANGE_EDGE = 'CHANGE_EDGE'
const CHANGE_ALIGNMENT = 'CHANGE_ALIGNMENT'
const HIDE_PANEL = 'HIDE_PANEL'
const SHOW_PANEL = 'SHOW_PANEL'

const SLIDE_STATUS = 'SLIDE_STATUS'

const NEXT_EDGE = 'NEXT_EDGE'
const NEXT_ALIGNMENT = 'NEXT_ALIGNMENT'
const UPDATING_POSITION = 'UPDATING_POSITION'
const UPDATE_POSITION = 'UPDATE_POSITION'

const SHOW_SETTINGS = 'SHOW_SETTINGS'
const HIDE_SETTINGS = 'HIDE_SETTINGS'

const START_ANIMATION = 'START_ANIMATION'

const MASK_GROW = 'MASK_GROW'

const NEXT_TASK_COUNT1 = 'NEXT_TASK_COUNT1'
const UPDATE_TASK_COUNT_1 = 'UPDATE_TASK_COUNT_1'
